instances:
  - name: talker
    commands: |
      ros2 run demo_nodes_cpp talker
  - name: listener
    commands: |
      ros2 run demo_nodes_py listener
  - name: foxglove-bridge
    superClient: "TRUE"
    commands: |
      ros2 launch foxglove_bridge foxglove_bridge_launch.xml port:=8765
  - name: play-kitti-bag
    commands: |
      ros2 bag play bags/kitti_2011_09_26_drive_0002_synced_rosbag_v2 --loop
    artifacts:
      - name: kitti-bag
        image: us-docker.pkg.dev/teknoir/gcr.io/ros-kitti-bag
        tag: jazzy-20260125-120641

# Values possible for ROS instances
defaults:
  image:
    repository: us-docker.pkg.dev/teknoir/gcr.io/ros
    tag: jazzy
  replicas: 1
  resources: {}
  hostWorkspacePath: /opt/teknoir/ros/default_ws
  commands: |
    ros2 run demo_nodes_cpp talker

  # Hidden settings for ROS instances

  # discoveryServerAddress can be used to override the default Discovery Server address
  # e.g., discoveryServerAddress: "custom-discovery-server:11811"

  # domainId can be used to set the ROS_DOMAIN_ID environment variable
  # e.g., domainId: 1

  # artifacts can be used to specify init containers for pre-loading data
  # e.g., artifacts:
  #         - name: custom-artifact
  #           image: us-docker.pkg.dev/teknoir/gcr.io/custom-artifact
  #           tag: latest
  #           commands:
  #             - echo "Downloading custom artifact..."

discoveryServer:
  enabled: true
  image:
    repository: us-docker.pkg.dev/teknoir/gcr.io/dds-discovery
    tag: jazzy
  replicas: 1
  resources: {}