{{- if .Values.discoveryServer.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-discovery-server
  labels:
    app: {{ .Release.Name }}-discovery-server
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-discovery-server
  ports:
    - name: udp-ds
      port: 11811
      targetPort: udp-ds
      protocol: UDP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-discovery-server
  labels:
    app: {{ .Release.Name }}-discovery-server
spec:
  replicas: {{ .Values.discoveryServer.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-discovery-server
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-discovery-server
    spec:
      containers:
        - name: discovery-server
          image: "{{ $.Values.discoveryServer.image.repository }}:{{ $.Values.defaults.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: udp-ds
              containerPort: 11811
              protocol: UDP
          securityContext:
            allowPrivilegeEscalation: false
            runAsNonRoot: true
            readOnlyRootFilesystem: false
            capabilities:
              drop: [ "ALL" ]
          resources:
            {{- toYaml (default $.Values.defaults.resources .resources) | nindent 12 }}
{{- end }}