{{- range $instance := .Values.instances }}
{{- if not $instance.nviros }}

{{- if not (empty $instance.nodePorts) }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ $.Release.Name }}-{{ $instance.name }}
  labels:
    app: {{ $.Release.Name }}-{{ $instance.name }}
spec:
  type: NodePort
  selector:
    app: {{ $.Release.Name }}-{{ $instance.name }}
  ports:
    {{- range $port := $instance.nodePorts }}
    - name: {{ $port.name }}
      port: {{ $port.port }}
      targetPort: {{ $port.targetPort }}
      nodePort: {{ $port.nodePort }}
      protocol: {{ default "TCP" $port.protocol }}
    {{- end }}
{{- end }}

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $.Release.Name }}-{{ $instance.name }}
  labels:
    app: {{ $.Release.Name }}-{{ $instance.name }}
spec:
  replicas: {{ default $.Values.defaults.replicas $instance.replicas }}
  selector:
    matchLabels:
      app: {{ $.Release.Name }}-{{ $instance.name }}
  template:
    metadata:
      labels:
        app: {{ $.Release.Name }}-{{ $instance.name }}
    spec:
      runtimeClassName: nvidia
      nodeSelector:
        {{- toYaml (default $.Values.defaults.nodeSelector $instance.nodeSelector) | nindent 8 }}
      {{- if not (empty $instance.artifacts) }}
      initContainers:
        {{- range $artifact := $instance.artifacts }}
        - name: init-container-{{ $artifact.name }}
          image: "{{ $artifact.image }}:{{ $artifact.tag }}"
          imagePullPolicy: Always
          {{- if not (empty $artifact.commands) }}
          command: [ "/bin/sh", "-c" ]
          args:
            - |
              {{- range $artifact.commands }}
              {{ . }}
              {{- end }}
          {{- end }}
          securityContext:
            runAsUser: 0
          volumeMounts:
            - name: workspace-volume
              mountPath: /ros_ws
        {{- end }}
      {{- end }}
      containers:
        - name: ros
          image: "{{ default $.Values.defaults.image.repository (default (dict "repository" $.Values.defaults.image.repository) $instance.image).repository }}:{{ default $.Values.defaults.image.tag (default (dict "tag" $.Values.defaults.image.tag) $instance.image).tag }}"
          imagePullPolicy: IfNotPresent
          args:
            - |
              {{- range (default $.Values.defaults.commands $instance.commands) }}
              {{ . }}
              {{- end }}
          env:
            - name: ROS_DOMAIN_ID
              value: {{ default "0" $instance.domainId | quote }}
            - name: ROS_LOCALHOST_ONLY
              value: "0"
            - name: RMW_IMPLEMENTATION
              value: "rmw_zenoh_cpp"
            - name: ZENOH_CONFIG_OVERRIDE
              value: 'connect/endpoints=["tcp/{{ .Release.Name }}-zenoh-router:{{ .Values.zenohRouter.ports.zenoh }}"]'
            - name: ZENOH_ROUTER_CHECK_ATTEMPTS
              value: "0"
          {{- if not (empty $instance.nodePorts) }}
          ports:
            {{- range $port := $instance.nodePorts }}
            - name: {{ $port.name }}
              containerPort: {{ $port.targetPort }}
              protocol: {{ default "TCP" $port.protocol }}
            {{- end }}
          {{- end }}
          resources:
            {{- toYaml (default $.Values.defaults.resources $instance.resources) | nindent 12 }}
          volumeMounts:
            - name: workspace-volume
              mountPath: /ros_ws
{{/*            - name: zenoh-config*/}}
{{/*              mountPath: /config*/}}
      volumes:
        - name: workspace-volume
          hostPath:
            path: "{{ default $.Values.defaults.hostWorkspacePath $instance.hostWorkspacePath }}"
            type: DirectoryOrCreate
{{/*        - name: zenoh-config*/}}
{{/*          configMap:*/}}
{{/*            name: {{ $.Release.Name }}-zenoh-config*/}}

{{- end }}
{{- end }}
