{{- if .Values.zenohRouter.enabled }}
---
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-zenoh-router
  labels:
    app: {{ .Release.Name }}-zenoh-router
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-zenoh-router
  ports:
    - name: tcp-zenoh
      port: {{ .Values.zenohRouter.ports.zenoh }}
      targetPort: tcp-zenoh
      protocol: TCP
    - name: ws-zenoh
      port: {{ .Values.zenohRouter.ports.websocket }}
      targetPort: ws-zenoh
      protocol: TCP
    - name: rest-api
      port: {{ .Values.zenohRouter.ports.rest }}
      targetPort: rest-api
      protocol: TCP

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-zenoh-router
  labels:
    app: {{ .Release.Name }}-zenoh-router
spec:
  replicas: {{ .Values.zenohRouter.replicas }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-zenoh-router
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-zenoh-router
    spec:
      nodeSelector:
        {{- toYaml $.Values.zenohRouter.nodeSelector | nindent 8 }}
      containers:
        - name: zenoh-router
          image: "{{ $.Values.zenohRouter.image.repository }}:{{ $.Values.zenohRouter.image.tag }}"
          imagePullPolicy: IfNotPresent
          ports:
            - name: tcp-zenoh
              containerPort: {{ .Values.zenohRouter.ports.zenoh }}
              protocol: TCP
            - name: ws-zenoh
              containerPort: {{ .Values.zenohRouter.ports.websocket }}
              protocol: TCP
            - name: rest-api
              containerPort: {{ .Values.zenohRouter.ports.rest }}
              protocol: TCP
          args: ["--config", "/config/router.json5"]
          volumeMounts:
            - name: zenoh-config
              mountPath: /config
          securityContext:
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: false
            capabilities:
              drop: [ "ALL" ]
          resources:
            {{- toYaml $.Values.zenohRouter.resources | nindent 12 }}
      volumes:
        - name: zenoh-config
          configMap:
            name: {{ $.Release.Name }}-zenoh-config
{{- end }}
