instances:
  - name: talker
    commands: |
      ros2 run demo_nodes_cpp talker
  - name: listener
    commands: |
      ros2 run demo_nodes_py listener

# Values possible for ROS instances
defaults:
  image:
    repository: us-docker.pkg.dev/teknoir/gcr.io/ros
    tag: jazzy
  replicas: 1
  resources: {}
  hostWorkspacePath: /opt/teknoir/ros/default_ws
  commands: |
    ros2 run demo_nodes_cpp talker
  # K8s NodePort range is typically 30000-32767
  # e.g., nodePorts:
  #        - name: http-fg-bridge
  #          port: 8765
  #          targetPort: 8765
  #          nodePort: 31765
  nodePorts: []

  # Hidden settings for ROS instances

  # discoveryServerAddress can be used to override the default Discovery Server address
  # e.g., discoveryServerAddress: "custom-discovery-server:11811"

  # domainId can be used to set the ROS_DOMAIN_ID environment variable
  # e.g., domainId: 1

  # superClient can be used to set the ROS_SUPER_CLIENT environment variable
  # e.g., superClient: "TRUE"

  # artifacts can be used to specify init containers for pre-loading data
  # e.g., artifacts:
  #         - name: custom-artifact
  #           image: us-docker.pkg.dev/teknoir/gcr.io/custom-artifact
  #           tag: latest
  #           commands:
  #             - echo "Downloading custom artifact..."

discoveryServer:
  enabled: true
  image:
    repository: us-docker.pkg.dev/teknoir/gcr.io/dds-discovery
    tag: jazzy-20260125-134403
  replicas: 1
  resources: {}