instances:
  - name: talker
    args:
      - ros2
      - run
      - demo_nodes_cpp
      - talker
  - name: listener
    args:
      - ros2
      - run
      - demo_nodes_py
      - listener

# Values possible for ROS instances
defaults:
  image:
    repository: us-docker.pkg.dev/teknoir/gcr.io/ros
    tag: jazzy
  replicas: 1
  args: []
  resources: {}
  # discoveryServerAddress can be used to override the default Discovery Server address
  # e.g., discoveryServerAddress: "custom-discovery-server:11811"
  # domainId can be used to set the ROS_DOMAIN_ID environment variable
  # e.g., domainId: 1

discoveryServer:
  enabled: true
  image:
    repository: us-docker.pkg.dev/teknoir/gcr.io/dds-discovery
    tag: jazzy
  replicas: 1
  resources: {}